In [875]:
## Manual changes - Renamed ROUNDS to rounds in Wimbeldon women's file
#Renamed ST1.1 for Wimbeldon women's file as there were 2 columns with the same name
#Renamed ST2.1 for US women's file as there were 2 columns with the same name
#Figure out how to do this in an automated manner

In [876]:
# Player 1 Name of Player 1 
# Player 2 Name of Player 2 
# Result Result of the match (0/1) - Referenced on Player 1 is Result = 1 if Player 1 wins (FNL.1>FNL.2) 
# FSP.1 First Serve Percentage for player 1 (Real Number) 
# FSW.1 First Serve Won by player 1 (Real Number) 
# SSP.1 Second Serve Percentage for player 1 (Real Number) 
# SSW.1 Second Serve Won by player 1 (Real Number) 
# ACE.1 Aces won by player 1 (Numeric-Integer) 
# DBF.1 Double Faults committed by player 1 (Numeric-Integer) 
# WNR.1 Winners earned by player 1 (Numeric) 
# UFE.1 Unforced Errors committed by player 1 (Numeric) 
# BPC.1 Break Points Created by player 1 (Numeric) 
# BPW.1 Break Points Won by player 1 (Numeric) 
# NPA.1 Net Points Attempted by player 1 (Numeric) 
# NPW.1 Net Points Won by player 1 (Numeric) 
# TPW.1 Total Points Won by player 1 (Numeric) 
# ST1.1 Set 1 result for Player 1 (Numeric-Integer) 
# ST2.1 Set 2 Result for Player 1 (Numeric-Integer) 
# ST3.1 Set 3 Result for Player 1 (Numeric-Integer) 
# ST4.1 Set 4 Result for Player 1 (Numeric-Integer) 
# ST5.1 Set 5 Result for Player 1 (Numeric-Integer) 
# FNL.1 Final Number of Games Won by Player 1 (Numeric-Integer) 
# FSP.2 First Serve Percentage for player 2 (Real Number) 
# FSW.2 First Serve Won by player 2 (Real Number) 
# SSP.2 Second Serve Percentage for player 2 (Real Number) 
# SSW.2 Second Serve Won by player 2 (Real Number) 
# ACE.2 Aces won by player 2 (Numeric-Integer) 
# DBF.2 Double Faults committed by player 2 (Numeric-Integer) 
# WNR.2 Winners earned by player 2 (Numeric) 
# UFE.2 Unforced Errors committed by player 2 (Numeric) 
# BPC.2 Break Points Created by player 2 (Numeric) 
# BPW.2 Break Points Won by player 2 (Numeric) 
# NPA.2 Net Points Attempted by player 2 (Numeric) 
# NPW.2 Net Points Won by player 2 (Numeric) 
# TPW.2 Total Points Won by player 2 (Numeric) 
# ST1.2 Set 1 result for Player 2 (Numeric-Integer) 
# ST2.2 Set 2 Result for Player 2 (Numeric-Integer) 
# ST3.2 Set 3 Result for Player 2 (Numeric-Integer) 
# ST4.2 Set 4 Result for Player 2 (Numeric-Integer) 
# ST5.2 Set 5 Result for Player 2 (Numeric-Integer) 
# FNL.2 Final Number of Games Won by Player 2 (Numeric-Integer) 
# Round Round of the tournament at which game is played (Numeric-Integer) 

# ACE.1         22
# ACE.2         22
# BPC.1          0
# BPC.2          0
# BPW.1          0
# BPW.2          0
# DBF.1          6
# DBF.2          6
# FNL.1        372
# FNL.2        372
# FNL1         560
# FNL2         560
# FSP.1          0
# FSP.2          0
# FSW.1          0
# FSW.2          0
# NPA.1         83
# NPA.2         83
# NPW.1         82
# NPW.2         82
# Result         0
# Round          0
# SSP.1          0
# SSP.2          0
# SSW.1          0
# SSW.2          0
# Sex            0
# TPW.1        312
# TPW.2        312
# UFE.1        125
# UFE.2        125
# WNR.1        125
# WNR.2        125
# slam_code      0
# ST1            0
# ST2            0
# ST3            0
# ST4            0
# ST5            0
# dtype: int64

# IMPORT

In [877]:
import os
import numpy as np
import random
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math
%matplotlib inline

from sklearn.neighbors import NearestNeighbors
from sklearn.decomposition import TruncatedSVD
from sklearn.preprocessing import scale
from sklearn import manifold
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [878]:
# Code - aus:1 french open:2 wimbeldon:3 and Us open:4
# 1 for women and 2 for Men
# Result : 1 for player winning and 0 for him/her losing
aus_men = pd.read_csv("data/AusOpen-men-2013.csv")
aus_women = pd.read_csv("data/AusOpen-women-2013.csv")
aus_men['slam_code'] = 1
aus_women['slam_code'] = 1
aus_women['Sex'] = 1
aus_men['Sex'] = 2


fre_men = pd.read_csv("data/FrenchOpen-men-2013.csv")
fre_women = pd.read_csv("data/FrenchOpen-women-2013.csv")
fre_men['slam_code'] = 2
fre_women['slam_code'] = 2
fre_women['Sex'] = 1
fre_men['Sex'] = 2

wim_men = pd.read_csv("data/Wimbledon-men-2013.csv")
wim_women = pd.read_csv("data/Wimbledon-women-2013.csv")
wim_men['slam_code'] = 3
wim_women['slam_code'] = 3
wim_women['Sex'] = 1
wim_men['Sex'] = 2

us_men = pd.read_csv("data/USOpen-men-2013.csv")
us_women = pd.read_csv("data/USOpen-women-2013.csv")
us_men['slam_code'] = 4
us_women['slam_code'] = 4
us_women['Sex'] = 1
us_men['Sex'] = 2

# CLEANSING

In [879]:
aus_men = aus_men.rename(columns={'FNL1': 'FNL.1', 'FNL2': 'FNL.2'})
aus_women = aus_women.rename(columns={'FNL1': 'FNL.1', 'FNL2': 'FNL.2'})

In [880]:
us_men = us_men.rename(columns={'FNL1': 'FNL.1', 'FNL2': 'FNL.2'})
us_women = us_women.rename(columns={'Player 1': 'Player1', 'Player 2': 'Player2'})

In [881]:
frames = [aus_men, fre_men, wim_men, us_men, aus_women, fre_women, wim_women, us_women]
tennis_merge = pd.concat(frames)

In [882]:
tennis_merge.columns[tennis_merge.isnull().any()]

Index(['FNL.1', 'FNL.2', 'ACE.1', 'DBF.1', 'WNR.1', 'UFE.1', 'BPC.1', 'BPW.1',
       'NPA.1', 'NPW.1', 'TPW.1', 'ST1.1', 'ST2.1', 'ST3.1', 'ST4.1', 'ST5.1',
       'ACE.2', 'DBF.2', 'WNR.2', 'UFE.2', 'BPC.2', 'BPW.2', 'NPA.2', 'NPW.2',
       'TPW.2', 'ST1.2', 'ST2.2', 'ST3.2', 'ST4.2', 'ST5.2'],
      dtype='object')

In [883]:
tennis_merge

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2,slam_code,Sex
0,Lukas Lacko,Novak Djokovic,1,0,0.0,3.0,61,35,39,18,...,8.0,9.0,101.0,6.0,7.0,6.0,NaN,NaN,1,2
1,Leonardo Mayer,Albert Montanes,1,1,3.0,0.0,61,31,39,13,...,NaN,NaN,42.0,1.0,3.0,1.0,NaN,NaN,1,2
2,Marcos Baghdatis,Denis Istomin,1,0,0.0,3.0,52,53,48,20,...,12.0,16.0,126.0,6.0,7.0,6.0,NaN,NaN,1,2
3,Dmitry Tursunov,Michael Russell,1,1,3.0,0.0,53,39,47,24,...,NaN,NaN,79.0,2.0,2.0,3.0,NaN,NaN,1,2
4,Juan Monaco,Ernests Gulbis,1,0,1.0,3.0,76,63,24,12,...,16.0,28.0,127.0,1.0,6.0,7.0,6.0,NaN,1,2
5,Santiago Giraldo,Sam Querrey,1,0,1.0,3.0,65,51,35,22,...,14.0,17.0,122.0,6.0,6.0,3.0,7.0,NaN,1,2
6,Dudi Sela,Jarkko Nieminen,1,0,2.0,3.0,68,73,32,24,...,25.0,36.0,173.0,3.0,7.0,6.0,6.0,6.0,1,2
7,Fabio Fognini,Alex Bogomolov Jr.,1,1,2.0,0.0,47,18,53,15,...,8.0,12.0,61.0,3.0,2.0,NaN,NaN,NaN,1,2
8,David Guez,Richard Gasquet,1,0,0.0,3.0,64,26,36,12,...,8.0,11.0,94.0,7.0,6.0,6.0,NaN,NaN,1,2
9,Nikolay Davydenko,Lukasz Kubot,1,1,3.0,2.0,77,76,23,11,...,NaN,NaN,141.0,6.0,3.0,6.0,3.0,4.0,1,2
10,Pablo Carreno Busta,Julien Benneteau,1,0,2.0,3.0,53,46,47,35,...,30.0,43.0,152.0,6.0,3.0,4.0,6.0,6.0,1,2
11,Tommy Robredo,Lukas Rosol,1,1,3.0,2.0,57,62,43,43,...,28.0,44.0,152.0,1.0,7.0,6.0,6.0,6.0,1,2
12,Samuel Groth,Vasek Pospisil,1,0,0.0,3.0,65,40,35,17,...,6.0,10.0,94.0,6.0,6.0,6.0,NaN,NaN,1,2
13,Nicolas Mahut,Matthew Ebden,1,0,2.0,3.0,64,63,36,23,...,28.0,37.0,131.0,6.0,7.0,4.0,0.0,6.0,1,2
14,Alejandro Falla,Mikhail Kukushkin,1,1,3.0,1.0,60,50,40,23,...,NaN,NaN,128.0,7.0,2.0,2.0,3.0,NaN,1,2
15,Stanislas Wawrinka,Andrey Golubev,1,1,2.0,0.0,63,20,37,6,...,6.0,12.0,37.0,4.0,1.0,NaN,NaN,NaN,1,2
16,Alejandro Gonzalez,David Ferrer,1,0,0.0,3.0,68,34,32,7,...,18.0,22.0,96.0,6.0,6.0,6.0,NaN,NaN,1,2
17,Steve Johnson,Adrian Mannarino,1,0,2.0,3.0,53,50,47,28,...,NaN,NaN,142.0,3.0,6.0,6.0,5.0,6.0,1,2
18,Ricardas Berankis,Alexandr Dolgopolov,1,0,0.0,3.0,50,39,50,26,...,12.0,12.0,114.0,7.0,7.0,6.0,NaN,NaN,1,2
19,Jeremy Chardy,Jesse Huta Galung,1,1,3.0,0.0,66,46,34,16,...,14.0,17.0,80.0,2.0,4.0,4.0,NaN,NaN,1,2
20,Jordan Thompson,Jerzy Janowicz,1,0,2.0,3.0,60,58,40,21,...,31.0,46.0,153.0,1.0,4.0,6.0,6.0,6.0,1,2
21,Albert Ramos,Pablo Andujar,1,0,0.0,3.0,61,32,39,10,...,NaN,NaN,97.0,6.0,6.0,6.0,NaN,NaN,1,2
22,Florian Mayer,Denis Kudla,1,1,3.0,0.0,58,36,42,22,...,12.0,20.0,78.0,4.0,2.0,4.0,NaN,NaN,1,2
23,Mikhail Youzhny,Jan-Lennard Struff,1,1,3.0,0.0,69,39,31,17,...,15.0,22.0,66.0,1.0,4.0,2.0,NaN,NaN,1,2
24,Guillermo Garcia-Lopez,Tommy Haas,1,1,2.0,0.0,58,27,42,11,...,10.0,10.0,55.0,5.0,2.0,NaN,NaN,NaN,1,2
25,Carlos Berlocq,Edouard Roger-Vasselin,1,0,1.0,3.0,57,49,43,32,...,NaN,NaN,163.0,6.0,7.0,6.0,6.0,NaN,1,2
26,Dominic Thiem,Joao Sousa,1,1,3.0,1.0,55,60,45,31,...,NaN,NaN,133.0,7.0,4.0,3.0,6.0,NaN,1,2
27,Kevin Anderson,Jiri Vesely,1,1,3.0,2.0,63,76,37,28,...,NaN,NaN,154.0,6.0,7.0,4.0,4.0,4.0,1,2
28,Ivo Karlovic,Ivan Dodig,1,0,0.0,3.0,66,55,34,18,...,24.0,35.0,108.0,7.0,6.0,7.0,NaN,NaN,1,2
29,Jan Hajek,Damir Dzumhur,1,0,0.0,3.0,73,31,27,6,...,NaN,NaN,95.0,6.0,6.0,6.0,NaN,NaN,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46,C Vandeweghe,C Suarez Navarro,2,0,0.0,2.0,47,14,53,10,...,2.0,2.0,NaN,6.0,6.0,NaN,NaN,NaN,4,1
47,L Robson,C Garcia,2,1,2.0,0.0,59,28,41,17,...,10.0,7.0,NaN,4.0,6.0,NaN,NaN,NaN,4,1
48,A Barty,A Pavlyuchenkova,2,0,0.0,2.0,52,13,48,10,...,NaN,NaN,NaN,6.0,6.0,NaN,NaN,NaN,4,1
49,P Kvitova,M Doi,1,1,2.0,1.0,73,47,27,11,...,6.0,5.0,NaN,2.0,6.0,1.0,NaN,NaN,4,1
50,C Wozniacki,Y Duan,1,1,2.0,0.0,69,28,31,12,...,9.0,8.0,NaN,2.0,5.0,NaN,NaN,NaN,4,1
51,D Pfizenmaier,V Azarenka,1,0,0.0,2.0,67,17,33,4,...,12.0,10.0,NaN,6.0,6.0,NaN,NaN,NaN,4,1
52,O Rogowska,S Errani,1,0,0.0,2.0,47,8,53,4,...,3.0,3.0,NaN,6.0,6.0,NaN,NaN,NaN,4,1
53,V Duval,S Stosur,1,1,2.0,1.0,63,49,37,19,...,22.0,16.0,NaN,7.0,4.0,4.0,NaN,NaN,4,1
54,A Ivanovic,A Tatishvili,1,1,2.0,0.0,62,17,48,11,...,5.0,3.0,NaN,2.0,0.0,NaN,NaN,NaN,4,1
55,J Goerges,C McHale,1,0,0.0,2.0,53,32,47,11,...,7.0,7.0,NaN,6.0,6.0,NaN,NaN,NaN,4,1
56,V Lepchenko,A Dulgheru,1,0,1.0,2.0,63,38,37,18,...,19.0,14.0,NaN,6.0,6.0,7.0,NaN,NaN,4,1
57,S Kuznetsova,M Burdette,1,1,2.0,0.0,63,26,37,12,...,9.0,5.0,NaN,3.0,5.0,NaN,NaN,NaN,4,1
58,B Jovanovski,A Petkovic,1,1,2.0,0.0,60,31,40,15,...,10.0,8.0,NaN,2.0,4.0,NaN,NaN,NaN,4,1
59,S Peng,Y Meusburger,1,1,2.0,0.0,54,18,46,16,...,11.0,7.0,NaN,3.0,4.0,NaN,NaN,NaN,4,1
60,A Cornet,M Koehler,1,1,2.0,0.0,53,19,47,18,...,3.0,3.0,NaN,3.0,2.0,NaN,NaN,NaN,4,1
61,H Watson,S Halep,1,0,1.0,2.0,54,29,46,16,...,5.0,3.0,NaN,4.0,6.0,6.0,NaN,NaN,4,1
62,K Flipkens,V Williams,1,0,0.0,2.0,46,15,54,7,...,22.0,15.0,NaN,6.0,6.0,NaN,NaN,NaN,4,1
63,A.Radwanska,S.Soler-Espinosa,1,1,2.0,0.0,72,26,28,6,...,NaN,34.0,NaN,1.0,2.0,NaN,NaN,NaN,4,1
64,S Williams,F Schiavone,1,1,2.0,0.0,51,13,49,12,...,6.0,3.0,NaN,0.0,1.0,NaN,NaN,NaN,4,1
65,O Govortsova,N Li,1,0,0.0,2.0,68,22,42,6,...,13.0,9.0,NaN,6.0,6.0,NaN,NaN,NaN,4,1
66,M Minella,S Stephens,1,0,1.0,2.0,65,43,35,18,...,19.0,13.0,NaN,4.0,6.0,7.0,NaN,NaN,4,1
67,J Jankovic,M Keys,1,1,2.0,0.0,64,28,36,14,...,13.0,6.0,NaN,3.0,4.0,NaN,NaN,NaN,4,1
68,L Robson,L Dominguez Lino,1,1,2.0,0.0,57,27,43,7,...,5.0,4.0,NaN,5.0,0.0,NaN,NaN,NaN,4,1
69,J Hampton,L Arruabarrena,1,1,2.0,0.0,61,27,39,13,...,8.0,4.0,NaN,4.0,2.0,NaN,NaN,NaN,4,1
70,V Dushevina,S Lisicki,1,0,0.0,2.0,54,21,46,14,...,12.0,8.0,NaN,6.0,7.0,NaN,NaN,NaN,4,1
71,P Ormaechea,K Date-Krumm,1,1,2.0,0.0,59,32,41,10,...,14.0,9.0,NaN,3.0,6.0,NaN,NaN,NaN,4,1
72,K Pliskova,E Bouchard,1,0,1.0,2.0,53,48,47,21,...,13.0,10.0,NaN,4.0,6.0,7.0,NaN,NaN,4,1
73,L Hradecka,A Kerber,1,0,0.0,2.0,49,17,51,4,...,6.0,5.0,NaN,6.0,6.0,NaN,NaN,NaN,4,1
74,L Davis,C Suarez Navarro,1,0,0.0,2.0,63,12,37,3,...,10.0,8.0,NaN,6.0,6.0,NaN,NaN,NaN,4,1
75,K Mladenovic,A Medina Garrigues,1,1,2.0,1.0,51,29,49,15,...,14.0,7.0,NaN,1.0,6.0,1.0,NaN,NaN,4,1

In [884]:
#Source:https://stackoverflow.com/a/39237712

tennis_merge = tennis_merge.reindex(
    columns = (['Player1','Player2'] + 
               list([a for a in tennis_merge.columns if a not in ('Player1','Player2')]
                   ) 
              )
)

In [885]:
tennis_feat.columns

Index(['Round', 'Result', 'FNL.1', 'FNL.2', 'FSP.1', 'FSW.1', 'SSP.1', 'SSW.1',
       'ACE.1', 'DBF.1', 'WNR.1', 'UFE.1', 'BPC.1', 'BPW.1', 'NPA.1', 'NPW.1',
       'FSP.2', 'FSW.2', 'SSP.2', 'SSW.2', 'ACE.2', 'DBF.2', 'WNR.2', 'UFE.2',
       'BPC.2', 'BPW.2', 'NPA.2', 'NPW.2', 'slam_code', 'Sex', 'ST1', 'ST2',
       'ST3', 'ST4', 'ST5'],
      dtype='object')

In [886]:
#Abandoned games men
tennis_merge[(tennis_merge['ST3.1'].isnull()) & (tennis_merge['Sex'] == 2)]

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2,slam_code,Sex
7,Fabio Fognini,Alex Bogomolov Jr.,1,1,2.0,0.0,47,18,53,15,...,8.0,12.0,61.0,3.0,2.0,NaN,NaN,NaN,1,2
15,Stanislas Wawrinka,Andrey Golubev,1,1,2.0,0.0,63,20,37,6,...,6.0,12.0,37.0,4.0,1.0,NaN,NaN,NaN,1,2
24,Guillermo Garcia-Lopez,Tommy Haas,1,1,2.0,0.0,58,27,42,11,...,10.0,10.0,55.0,5.0,2.0,NaN,NaN,NaN,1,2
40,Martin Klizan,John Isner,1,1,2.0,0.0,54,25,46,21,...,5.0,10.0,52.0,2.0,6.0,NaN,NaN,NaN,1,2
63,Rafael Nadal,Bernard Tomic,1,1,1.0,0.0,62,14,38,6,...,3.0,5.0,24.0,4.0,NaN,NaN,NaN,NaN,1,2
59,Alejandro Falla,Grigor Dimitrov,1,0,0.0,2.0,54,10,46,7,...,6.0,7.0,48.0,6.0,1.0,NaN,NaN,NaN,2,2
91,Dmitry Tursunov,Victor Hanescu,2,0,0.0,2.0,59,31,41,9,...,5.0,6.0,66.0,6.0,6.0,NaN,NaN,NaN,2,2
65,Guillaume Rufin,Dmitry Tursunov,1,0,0.0,2.0,43,14,57,12,...,NaN,NaN,51.0,7.0,1.0,NaN,NaN,NaN,4,2

In [887]:
#Abandoned games women
tennis_merge[(tennis_merge['ST2.1'].isnull()) & (tennis_merge['Sex'] == 1)]

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2,slam_code,Sex
44,Alize Cornet,Polona Hercog,1,0,NaN,NaN,75,3,25,1,...,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,1,1
76,Ashleigh Barty,Maria Kirilenko,2,0,0.0,1.0,61,6,39,4,...,5.0,6.0,18.0,3.0,NaN,NaN,NaN,NaN,2,1
77,Kaia Kanepi,Stefanie Voegele,2,1,1.0,0.0,71,20,29,5,...,4.0,6.0,39.0,5.0,NaN,NaN,NaN,NaN,2,1

In [888]:
## Removing abandoned games
tennis_merge = tennis_merge[-((tennis_merge['ST3.1'].isnull()) & (tennis_merge['Sex'] == 2))] #For men

tennis_merge = tennis_merge[-((tennis_merge['ST2.1'].isnull()) & (tennis_merge['Sex'] == 1))] #For women

In [889]:
## Feature engineering1: Find difference between games won in sets as this would indicate who won the set
# If positive: Player 1 wins the set Else Player 2
# The value is NaN if the set did not occur, in which case we set it to 0(0 can never occur otherwise)
tennis_merge['ST1'] = tennis_merge['ST1.1'] - tennis_merge['ST1.2']
tennis_merge['ST2'] = tennis_merge['ST2.1'] - tennis_merge['ST2.2']
tennis_merge['ST3'] = tennis_merge['ST3.1'] - tennis_merge['ST3.2']
tennis_merge['ST4'] = tennis_merge['ST4.1'] - tennis_merge['ST4.2']
tennis_merge['ST5'] = tennis_merge['ST5.1'] - tennis_merge['ST5.2']

In [890]:
## Replace NaN with 0s
tennis_merge['ST3'].fillna(0, inplace=True)
tennis_merge['ST4'].fillna(0, inplace=True)
tennis_merge['ST5'].fillna(0, inplace=True)

In [891]:
tennis_merge.columns

Index(['Player1', 'Player2', 'Round', 'Result', 'FNL.1', 'FNL.2', 'FSP.1',
       'FSW.1', 'SSP.1', 'SSW.1', 'ACE.1', 'DBF.1', 'WNR.1', 'UFE.1', 'BPC.1',
       'BPW.1', 'NPA.1', 'NPW.1', 'TPW.1', 'ST1.1', 'ST2.1', 'ST3.1', 'ST4.1',
       'ST5.1', 'FSP.2', 'FSW.2', 'SSP.2', 'SSW.2', 'ACE.2', 'DBF.2', 'WNR.2',
       'UFE.2', 'BPC.2', 'BPW.2', 'NPA.2', 'NPW.2', 'TPW.2', 'ST1.2', 'ST2.2',
       'ST3.2', 'ST4.2', 'ST5.2', 'slam_code', 'Sex', 'ST1', 'ST2', 'ST3',
       'ST4', 'ST5'],
      dtype='object')

In [974]:
#removing names of players as we aren't considering ranking here
# removing set info cause we have created another column
# removing Total points won cause there are too many missing values
rem_cols = ['Player1','Player2','TPW.1','TPW.2','FNL.1','FNL.2',
            'ST1.1','ST2.1','ST3.1','ST4.1','ST5.1',
            'ST1.2','ST2.2','ST3.2','ST4.2','ST5.2','ST1','ST2','ST3','ST4','ST5']

tennis_feat = tennis_merge.drop(rem_cols,axis  = 1,inplace = False) #removes columns

tennis_feat = shuffle(tennis_feat) #shuffles

#convert numeric to categorical
col_names = ['Round','slam_code','Sex','Result']
for col in col_names:
    tennis_feat[col] = tennis_feat[col].astype('category',copy=False)
    
#Train-test split. 30% for test
train,test = train_test_split(tennis_feat,test_size = 0.3)

In [975]:
tennis_feat[tennis_feat.columns[:]].isnull().sum().sort_values()

Round          0
BPW.2          0
BPC.2          0
SSW.2          0
SSP.2          0
FSW.2          0
FSP.2          0
slam_code      0
BPW.1          0
BPC.1          0
Sex            0
SSW.1          0
SSP.1          0
FSW.1          0
Result         0
FSP.1          0
DBF.2          6
DBF.1          6
ACE.1         22
ACE.2         22
NPW.2         82
NPW.1         82
NPA.2         83
NPA.1         83
WNR.2        125
UFE.1        125
UFE.2        125
WNR.1        125
dtype: int64

In [976]:
#convert numeric to categorical
col_names = ['Round','slam_code','Sex','Result']
for col in col_names:
    tennis_feat[col] = tennis_feat[col].astype('category',copy=False)

In [977]:
### Imputing mean values for men and women separately
## for columns - ACES, Net point won, Net points attempted, Winners hit and Unforced errors
## This is because this usually fluctates around the mean value for men's and women's tennis
print("Median for Winners player 1(MEN)",tennis_feat[tennis_feat["Sex"] == 2]["WNR.1"].median())
print("Median for Winners player 2(MEN)",tennis_feat[tennis_feat["Sex"] == 2]["WNR.2"].median())

print("Median for Ace player 1(WOMEN)",tennis_feat[tennis_feat["Sex"] == 1]["ACE.1"].median())
print("Median for Ace player 2(WOMEN)",tennis_feat[tennis_feat["Sex"] == 1]["ACE.2"].median())

print("Median for Net points attempted 1(WOMEN)",tennis_feat[tennis_feat["Sex"] == 1]["NPA.1"].median())
print("Median for Net points attempted 2(WOMEN)",tennis_feat[tennis_feat["Sex"] == 1]["NPA.2"].median())

print("Median for Net points attempted 1(MEN)",tennis_feat[tennis_feat["Sex"] == 2]["NPA.1"].median())
print("Median for Net points attempted 2(MEN)",tennis_feat[tennis_feat["Sex"] == 2]["NPA.2"].median())

print("Median for Net points won 1(WOMEN)",tennis_feat[tennis_feat["Sex"] == 1]["NPW.1"].median())
print("Median for Net points won 2(WOMEN)",tennis_feat[tennis_feat["Sex"] == 1]["NPW.2"].median())

print("Median for Net points Won 1(MEN)",tennis_feat[tennis_feat["Sex"] == 2]["NPW.1"].median())
print("Median for Net points Won 2(MEN)",tennis_feat[tennis_feat["Sex"] == 2]["NPW.2"].median())

Median for Winners player 1(MEN) 35.0
Median for Winners player 2(MEN) 36.0
Median for Ace player 1(WOMEN) 2.0
Median for Ace player 2(WOMEN) 2.0
Median for Net points attempted 1(WOMEN) 9.0
Median for Net points attempted 2(WOMEN) 9.0
Median for Net points attempted 1(MEN) 17.0
Median for Net points attempted 2(MEN) 18.0
Median for Net points won 1(WOMEN) 9.5
Median for Net points won 2(WOMEN) 9.0
Median for Net points Won 1(MEN) 22.0
Median for Net points Won 2(MEN) 22.0

In [978]:
#src: https://stackoverflow.com/a/21463854
tennis_feat["NPW.1"] = tennis_feat["NPW.1"].fillna(round(tennis_feat.groupby("Sex")["NPW.1"].transform("median"),2))
tennis_feat["NPW.2"] = tennis_feat["NPW.2"].fillna(round(tennis_feat.groupby("Sex")["NPW.2"].transform("median"),2))

tennis_feat["NPA.1"] = tennis_feat["NPA.1"].fillna(tennis_feat.groupby("Sex")["NPA.1"].transform("median"))
tennis_feat["NPA.2"] = tennis_feat["NPA.2"].fillna(tennis_feat.groupby("Sex")["NPA.2"].transform("median"))

tennis_feat["ACE.1"] = tennis_feat["ACE.1"].fillna(tennis_feat.groupby("Sex")["ACE.1"].transform("median"))
tennis_feat["ACE.2"] = tennis_feat["ACE.2"].fillna(tennis_feat.groupby("Sex")["ACE.2"].transform("median"))

tennis_feat["WNR.1"] = tennis_feat["WNR.1"].fillna(tennis_feat.groupby("Sex")["WNR.1"].transform("median"))
tennis_feat["WNR.2"] = tennis_feat["WNR.2"].fillna(tennis_feat.groupby("Sex")["WNR.2"].transform("median"))

tennis_feat["DBF.1"] = tennis_feat["DBF.1"].fillna(tennis_feat.groupby("Sex")["DBF.1"].transform("median"))
tennis_feat["DBF.2"] = tennis_feat["DBF.2"].fillna(tennis_feat.groupby("Sex")["DBF.2"].transform("median"))

tennis_feat["UFE.1"] = tennis_feat["UFE.1"].fillna(tennis_feat.groupby("Sex")["UFE.1"].transform("median"))
tennis_feat["UFE.2"] = tennis_feat["UFE.2"].fillna(tennis_feat.groupby("Sex")["UFE.2"].transform("median"))

In [979]:
tennis_feat[tennis_feat.columns[:]].isnull().sum().sort_values()

Round        0
NPW.2        0
NPA.2        0
BPW.2        0
BPC.2        0
UFE.2        0
WNR.2        0
DBF.2        0
ACE.2        0
SSW.2        0
SSP.2        0
FSW.2        0
FSP.2        0
NPW.1        0
NPA.1        0
BPW.1        0
BPC.1        0
UFE.1        0
WNR.1        0
DBF.1        0
ACE.1        0
SSW.1        0
SSP.1        0
FSW.1        0
FSP.1        0
Result       0
slam_code    0
Sex          0
dtype: int64

In [980]:
tennis_feat.shape

(932, 28)

In [981]:
tennis_feat.dtypes

Round        category
Result       category
FSP.1           int64
FSW.1           int64
SSP.1           int64
SSW.1           int64
ACE.1         float64
DBF.1         float64
WNR.1         float64
UFE.1         float64
BPC.1         float64
BPW.1         float64
NPA.1         float64
NPW.1         float64
FSP.2           int64
FSW.2           int64
SSP.2           int64
SSW.2           int64
ACE.2         float64
DBF.2         float64
WNR.2         float64
UFE.2         float64
BPC.2         float64
BPW.2         float64
NPA.2         float64
NPW.2         float64
slam_code    category
Sex          category
dtype: object

In [982]:
tennis_feat.select_dtypes(include=[np.number]).columns

Index(['FSP.1', 'FSW.1', 'SSP.1', 'SSW.1', 'ACE.1', 'DBF.1', 'WNR.1', 'UFE.1',
       'BPC.1', 'BPW.1', 'NPA.1', 'NPW.1', 'FSP.2', 'FSW.2', 'SSP.2', 'SSW.2',
       'ACE.2', 'DBF.2', 'WNR.2', 'UFE.2', 'BPC.2', 'BPW.2', 'NPA.2', 'NPW.2'],
      dtype='object')

Game of tennis in grand slams is best of 5 sets. In case a player wins the first 3 sets the values for set 4 and set 5 are NAs. To ensure rows aren't excluded set them to -1

# ANALYSIS

In [983]:
def scale_matrix(matrix,num_feat,non_num_feat):
    scl = StandardScaler()
    scl_mat = scl.fit_transform(matrix[num_feat])
    temp = np.concatenate((scl_mat,
                    matrix[non_num_feat].as_matrix().astype('int')),
                   axis = 1)
#     temp = temp.astype(int)
    return temp

In [984]:
#numeric columns
numeric_features = tennis_feat.select_dtypes(include=[np.number]).columns

#non-numeric columns
non_num_features = tennis_feat.select_dtypes(exclude=[np.number]).columns

In [985]:
Features = list(numeric_features)+(list(non_num_features))

In [986]:
print(Features)

['FSP.1', 'FSW.1', 'SSP.1', 'SSW.1', 'ACE.1', 'DBF.1', 'WNR.1', 'UFE.1', 'BPC.1', 'BPW.1', 'NPA.1', 'NPW.1', 'FSP.2', 'FSW.2', 'SSP.2', 'SSW.2', 'ACE.2', 'DBF.2', 'WNR.2', 'UFE.2', 'BPC.2', 'BPW.2', 'NPA.2', 'NPW.2', 'Round', 'Result', 'slam_code', 'Sex']

In [987]:
tennis_scaled = pd.DataFrame(scale_matrix(tennis_feat,numeric_features,non_num_features))

In [988]:
tennis_scaled.columns = Features

In [989]:
col_names = ['Round','slam_code','Sex','Result']
for col in col_names:
    tennis_scaled[col] = tennis_scaled[col].astype('category',copy=False)

In [990]:
tennis_dummy = pd.get_dummies(tennis_scaled)

In [991]:
tennis_dummy.columns

Index(['FSP.1', 'FSW.1', 'SSP.1', 'SSW.1', 'ACE.1', 'DBF.1', 'WNR.1', 'UFE.1',
       'BPC.1', 'BPW.1', 'NPA.1', 'NPW.1', 'FSP.2', 'FSW.2', 'SSP.2', 'SSW.2',
       'ACE.2', 'DBF.2', 'WNR.2', 'UFE.2', 'BPC.2', 'BPW.2', 'NPA.2', 'NPW.2',
       'Round_1.0', 'Round_2.0', 'Round_3.0', 'Round_4.0', 'Round_5.0',
       'Round_6.0', 'Round_7.0', 'Result_0.0', 'Result_1.0', 'slam_code_1.0',
       'slam_code_2.0', 'slam_code_3.0', 'slam_code_4.0', 'Sex_1.0',
       'Sex_2.0'],
      dtype='object')

In [992]:
tennis_dummy['Result_0.0'].sum()

473

In [993]:
rem_cols_dummy = ['Result_0.0','Sex_2.0','slam_code_1.0','slam_code_2.0',
                  'slam_code_3.0','slam_code_4.0']

tennis_final = tennis_dummy.drop(rem_cols_dummy,axis  = 1,inplace = False)

In [994]:
tennis_final.columns

Index(['FSP.1', 'FSW.1', 'SSP.1', 'SSW.1', 'ACE.1', 'DBF.1', 'WNR.1', 'UFE.1',
       'BPC.1', 'BPW.1', 'NPA.1', 'NPW.1', 'FSP.2', 'FSW.2', 'SSP.2', 'SSW.2',
       'ACE.2', 'DBF.2', 'WNR.2', 'UFE.2', 'BPC.2', 'BPW.2', 'NPA.2', 'NPW.2',
       'Round_1.0', 'Round_2.0', 'Round_3.0', 'Round_4.0', 'Round_5.0',
       'Round_6.0', 'Round_7.0', 'Result_1.0', 'Sex_1.0'],
      dtype='object')

In [995]:
#Train-test split. 30% for test
train_valid,test = train_test_split(tennis_final,test_size = 0.3,random_state=12345)
train,valid = train_test_split(train_valid,test_size = 0.3,random_state=12345)

In [996]:
Xtrain = train.iloc[:, train.columns != "Result_1.0"]
ytrain = train.iloc[:, train.columns == "Result_1.0"]

Xvalid = valid.iloc[:, valid.columns != "Result_1.0"]
yvalid = valid.iloc[:, valid.columns == "Result_1.0"]

Xtest = test.iloc[:, test.columns != "Result_1.0"]
ytest = test.iloc[:, test.columns == "Result_1.0"]

In [997]:
Xtrain.columns

Index(['FSP.1', 'FSW.1', 'SSP.1', 'SSW.1', 'ACE.1', 'DBF.1', 'WNR.1', 'UFE.1',
       'BPC.1', 'BPW.1', 'NPA.1', 'NPW.1', 'FSP.2', 'FSW.2', 'SSP.2', 'SSW.2',
       'ACE.2', 'DBF.2', 'WNR.2', 'UFE.2', 'BPC.2', 'BPW.2', 'NPA.2', 'NPW.2',
       'Round_1.0', 'Round_2.0', 'Round_3.0', 'Round_4.0', 'Round_5.0',
       'Round_6.0', 'Round_7.0', 'Sex_1.0'],
      dtype='object')

In [998]:
Xtrain = Xtrain.as_matrix()
Xvalid = Xvalid.as_matrix()
Xtest = Xtest.as_matrix()
ytrain = np.ravel(ytrain.as_matrix())
yvalid = np.ravel(yvalid.as_matrix())
ytest = np.ravel(ytest.as_matrix())

In [999]:
XCross = np.concatenate((Xtrain,Xvalid))
yCross = np.concatenate((ytrain,yvalid))

In [1000]:
from sklearn.grid_search import GridSearchCV
grid = {
        'C': np.power(10.0, np.arange(-6, 6))
    }
clf = LogisticRegression(penalty='l2', random_state=1234)
gs = GridSearchCV(clf, grid,cv=20)
gs.fit(XCross, yCross)

print ('gs.best_score_:', gs.best_score_)
print('Param value',gs.best_params_)
gs.grid_scores_

gs.best_score_: 0.9371165644171779
Param value {'C': 1.0}

[mean: 0.88804, std: 0.06081, params: {'C': 9.9999999999999995e-07},
 mean: 0.88804, std: 0.06081, params: {'C': 1.0000000000000001e-05},
 mean: 0.88957, std: 0.05671, params: {'C': 0.0001},
 mean: 0.90184, std: 0.05040, params: {'C': 0.001},
 mean: 0.92791, std: 0.03896, params: {'C': 0.01},
 mean: 0.92945, std: 0.04010, params: {'C': 0.10000000000000001},
 mean: 0.93712, std: 0.03540, params: {'C': 1.0},
 mean: 0.93098, std: 0.03838, params: {'C': 10.0},
 mean: 0.92791, std: 0.03896, params: {'C': 100.0},
 mean: 0.92791, std: 0.03896, params: {'C': 1000.0},
 mean: 0.92791, std: 0.03896, params: {'C': 10000.0},
 mean: 0.92791, std: 0.03896, params: {'C': 100000.0}]

In [1001]:
grid = {
        'C': np.power(10.0, np.arange(-6, 6))
    }
clf = LogisticRegression(penalty='l1', random_state=1234)
gs = GridSearchCV(clf, grid, cv=20)
gs.fit(XCross, yCross)

print ('gs.best_score_:', gs.best_score_)
print('Param value',gs.best_params_)
gs.grid_scores_

gs.best_score_: 0.9355828220858896
Param value {'C': 1.0}

[mean: 0.50920, std: 0.00742, params: {'C': 9.9999999999999995e-07},
 mean: 0.50920, std: 0.00742, params: {'C': 1.0000000000000001e-05},
 mean: 0.50920, std: 0.00742, params: {'C': 0.0001},
 mean: 0.50920, std: 0.00742, params: {'C': 0.001},
 mean: 0.90337, std: 0.04225, params: {'C': 0.01},
 mean: 0.93098, std: 0.05261, params: {'C': 0.10000000000000001},
 mean: 0.93558, std: 0.03172, params: {'C': 1.0},
 mean: 0.92945, std: 0.03616, params: {'C': 10.0},
 mean: 0.92791, std: 0.03896, params: {'C': 100.0},
 mean: 0.92791, std: 0.03896, params: {'C': 1000.0},
 mean: 0.92791, std: 0.03896, params: {'C': 10000.0},
 mean: 0.92791, std: 0.03896, params: {'C': 100000.0}]

In [1002]:
from sklearn.grid_search import GridSearchCV
grid = {
        'C': np.power(10.0, np.arange(0, 3))
    }
clf = LogisticRegression(penalty='l2', random_state=1234)
gs = GridSearchCV(clf, grid,cv=20)
gs.fit(XCross, yCross)

print ('gs.best_score_:', gs.best_score_)
print('Param value',gs.best_params_)
gs.grid_scores_

gs.best_score_: 0.9371165644171779
Param value {'C': 1.0}

[mean: 0.93712, std: 0.03540, params: {'C': 1.0},
 mean: 0.93098, std: 0.03838, params: {'C': 10.0},
 mean: 0.92791, std: 0.03896, params: {'C': 100.0}]

In [1003]:
grid = {
        'C': np.power(10.0, np.arange(-2, 1))
    }
clf = LogisticRegression(penalty='l1', random_state=1234)
gs = GridSearchCV(clf, grid, cv=20)
gs.fit(XCross, yCross)

print ('gs.best_score_:', gs.best_score_)
print('Param value',gs.best_params_)
gs.grid_scores_

gs.best_score_: 0.9355828220858896
Param value {'C': 1.0}

[mean: 0.90337, std: 0.04225, params: {'C': 0.01},
 mean: 0.93098, std: 0.05261, params: {'C': 0.10000000000000001},
 mean: 0.93558, std: 0.03172, params: {'C': 1.0}]

In [1004]:
lg = LogisticRegression(penalty = 'l1',C=1)
lg.fit(Xtrain,ytrain)

print("Num Features: %d",lg.coef_)
print("Selected Features: %s",lg.intercept_)
print('Actual number of iterations for all classes: ', lg.n_iter_)

# Compute the training accuracy
print('Mean accuracy  of training data: {0:.2f}%'
      .format(100 * lg.score(Xtrain, ytrain)))
# # Compute the validation accuracy
print('Mean accuracy  of validation data: {0:.2f}'
      .format(100 * lg.score(Xvalid, yvalid)))
# # Compute the test accuracy
print('Mean accuracy  of test data: {0:.2f}'
      .format(100 * lg.score(Xtest, ytest)))

Num Features: %d [[ 0.01401493  3.22765251 -0.1275581   1.86100415 -0.25582663 -0.23677262
   1.08268567 -0.86712406  1.33388027  1.53536769  0.13843675 -0.17533785
   0.         -3.73869644  0.         -1.88233649  0.          0.41888247
  -0.40416467  0.32982991 -1.24651392 -1.00830938  0.          0.10598907
  -0.16869937  0.07611551 -0.08623677  0.          0.          0.          0.
   0.        ]]
Selected Features: %s [ 0.]
Actual number of iterations for all classes:  [19]
Mean accuracy  of training data: 95.39%
Mean accuracy  of validation data: 94.39
Mean accuracy  of test data: 93.93

In [1005]:
train.iloc[:, train.columns != "Result_1.0"].columns

Index(['FSP.1', 'FSW.1', 'SSP.1', 'SSW.1', 'ACE.1', 'DBF.1', 'WNR.1', 'UFE.1',
       'BPC.1', 'BPW.1', 'NPA.1', 'NPW.1', 'FSP.2', 'FSW.2', 'SSP.2', 'SSW.2',
       'ACE.2', 'DBF.2', 'WNR.2', 'UFE.2', 'BPC.2', 'BPW.2', 'NPA.2', 'NPW.2',
       'Round_1.0', 'Round_2.0', 'Round_3.0', 'Round_4.0', 'Round_5.0',
       'Round_6.0', 'Round_7.0', 'Sex_1.0'],
      dtype='object')

In [1011]:
col_list = list(train.iloc[:, train.columns != "Result_1.0"].columns)

In [1023]:
coef = np.ravel(lg.coef_).tolist()

In [1028]:
a = list(zip(col_list,coef))

In [1036]:
#https://stackoverflow.com/a/7142240S
a.sort(key = lambda t: t[1],reverse=True)

In [1037]:
a

[('FSW.1', 3.2276525054755894),
 ('SSW.1', 1.8610041465028875),
 ('BPW.1', 1.5353676857241372),
 ('BPC.1', 1.33388026534039),
 ('WNR.1', 1.0826856689222966),
 ('DBF.2', 0.41888246950011365),
 ('UFE.2', 0.32982990958098646),
 ('NPA.1', 0.13843675001271408),
 ('NPW.2', 0.10598907435515424),
 ('Round_2.0', 0.07611550994660726),
 ('FSP.1', 0.014014926215147942),
 ('FSP.2', 0.0),
 ('SSP.2', 0.0),
 ('ACE.2', 0.0),
 ('NPA.2', 0.0),
 ('Round_4.0', 0.0),
 ('Round_5.0', 0.0),
 ('Round_6.0', 0.0),
 ('Round_7.0', 0.0),
 ('Sex_1.0', 0.0),
 ('Round_3.0', -0.08623676567774044),
 ('SSP.1', -0.1275581037818527),
 ('Round_1.0', -0.16869937069981128),
 ('NPW.1', -0.17533785037855132),
 ('DBF.1', -0.2367726232606303),
 ('ACE.1', -0.255826632481858),
 ('WNR.2', -0.4041646652208412),
 ('UFE.1', -0.8671240555626746),
 ('BPW.2', -1.0083093826885756),
 ('BPC.2', -1.2465139248201333),
 ('SSW.2', -1.882336490760376),
 ('FSW.2', -3.7386964386924415)]